package br.com.codecacto.locadora.core.ui.strings

object Strings {
    // App
    const val APP_NAME = "LocAki"
    const val APP_VERSION = "Versão 1.0.0"
    const val APP_DESCRIPTION = "Controle de Locações"

    // Navigation
    const val NAV_LOCACOES = "Locações"
    const val NAV_ENTREGAS = "Entregas"
    const val NAV_RECEBER = "Receber"
    const val NAV_MENU = "Menu"
    const val NAV_LOCAR = "Locar"

    // Menu Screen
    const val MENU_TITLE = "Menu"
    const val MENU_SUBTITLE = "Configurações e cadastros"
    const val MENU_CLIENTES = "Clientes"
    const val MENU_CLIENTES_SUBTITLE = "Gerenciar clientes"
    const val MENU_EQUIPAMENTOS = "Equipamentos"
    const val MENU_EQUIPAMENTOS_SUBTITLE = "Gerenciar equipamentos"
    const val MENU_CONFIGURACOES = "Configurações"
    const val MENU_CONFIGURACOES_SUBTITLE = "Alterar senha e email"
    const val MENU_SAIR = "Sair"
    const val MENU_SAIR_SUBTITLE = "Encerrar sessão"
    const val MENU_DADOS_PRIVACIDADE = "Dados e Privacidade"
    const val MENU_DADOS_PRIVACIDADE_SUBTITLE = "Termos, política e conta"
    const val MENU_PERFIL = "Meu Perfil"
    const val MENU_PERFIL_SUBTITLE = "Alterar nome"
    const val MENU_DADOS_COMPROVANTE = "Dados do Comprovante"
    const val MENU_DADOS_COMPROVANTE_SUBTITLE = "Informações para recibos"

    // Profile Screen
    const val PROFILE_TITLE = "Meu Perfil"
    const val PROFILE_SUBTITLE = "Atualize suas informações"
    const val PROFILE_NOME = "Nome"
    const val PROFILE_NOME_PLACEHOLDER = "Digite seu nome"
    const val PROFILE_SALVAR = "Salvar Alterações"
    const val PROFILE_SUCESSO = "Perfil atualizado com sucesso!"
    const val PROFILE_ERRO = "Erro ao atualizar perfil"
    const val PROFILE_ERRO_NOME_VAZIO = "Digite seu nome"
    const val PROFILE_ERRO_NOME_CURTO = "Nome muito curto"
    const val PROFILE_ERRO_NOME_IGUAL = "O nome deve ser diferente do atual"

    // Dados Comprovante Screen
    const val DADOS_COMPROVANTE_TITLE = "Dados do Comprovante"
    const val DADOS_COMPROVANTE_SUBTITLE = "Informações para os recibos"
    const val DADOS_COMPROVANTE_NOTA = "Esses dados aparecerão nos comprovantes e recibos gerados pelo app."
    const val DADOS_COMPROVANTE_NOME = "Nome / Razão Social"
    const val DADOS_COMPROVANTE_NOME_PLACEHOLDER = "Ex: LocAki ou João da Silva"
    const val DADOS_COMPROVANTE_CPF = "CPF"
    const val DADOS_COMPROVANTE_CPF_PLACEHOLDER = "000.000.000-00"
    const val DADOS_COMPROVANTE_CNPJ = "CNPJ"
    const val DADOS_COMPROVANTE_CNPJ_PLACEHOLDER = "00.000.000/0000-00"
    const val DADOS_COMPROVANTE_TELEFONE = "Telefone"
    const val DADOS_COMPROVANTE_TELEFONE_PLACEHOLDER = "(00) 00000-0000"
    const val DADOS_COMPROVANTE_EMAIL = "E-mail"
    const val DADOS_COMPROVANTE_EMAIL_PLACEHOLDER = "contato@empresa.com"
    const val DADOS_COMPROVANTE_ENDERECO = "Endereço"
    const val DADOS_COMPROVANTE_ENDERECO_PLACEHOLDER = "Rua, número, bairro, cidade"
    const val DADOS_COMPROVANTE_SALVAR = "Salvar Dados"
    const val DADOS_COMPROVANTE_SUCESSO = "Dados salvos com sucesso!"
    const val DADOS_COMPROVANTE_ERRO = "Erro ao salvar dados"
    const val DADOS_COMPROVANTE_CPF_INVALIDO = "CPF inválido"
    const val DADOS_COMPROVANTE_CNPJ_INVALIDO = "CNPJ inválido"
    const val DADOS_COMPROVANTE_MOMENTO_PAGAMENTO = "Momento do Pagamento (Padrão)"
    const val DADOS_COMPROVANTE_MOMENTO_PAGAMENTO_NOTA = "Define quando o recebimento será gerado por padrão nas novas locações"

    // Momento Pagamento
    const val MOMENTO_PAGAMENTO_NO_INICIO = "No Início"
    const val MOMENTO_PAGAMENTO_NO_VENCIMENTO = "No Vencimento"
    const val NOVA_LOCACAO_MOMENTO_PAGAMENTO = "Momento do Pagamento"

    // Menu - Novas opções
    const val MENU_HORARIO_NOTIFICACAO = "Horário de Notificação"
    const val MENU_HORARIO_NOTIFICACAO_SUBTITLE = "Agendar verificação diária"
    const val MENU_MOMENTO_PAGAMENTO = "Momento do Pagamento"
    const val MENU_MOMENTO_PAGAMENTO_SUBTITLE = "Quando gerar recebimentos"

    // Horário Notificação Screen
    const val HORARIO_NOTIFICACAO_TITLE = "Horário de Notificação"
    const val HORARIO_NOTIFICACAO_SUBTITLE = "Configure a verificação diária"
    const val HORARIO_NOTIFICACAO_NOTA = "O app verificará diariamente se há recebimentos vencidos ou próximos do vencimento e enviará notificações."
    const val HORARIO_NOTIFICACAO_LABEL = "Horário da verificação"
    const val HORARIO_NOTIFICACAO_SALVAR = "Salvar Horário"
    const val HORARIO_NOTIFICACAO_SUCESSO = "Horário salvo com sucesso!"
    const val HORARIO_NOTIFICACAO_ERRO = "Erro ao salvar horário"

    // Momento Pagamento Screen
    const val MOMENTO_PAGAMENTO_TITLE = "Momento do Pagamento"
    const val MOMENTO_PAGAMENTO_SUBTITLE = "Quando gerar recebimentos"
    const val MOMENTO_PAGAMENTO_NOTA = "Define quando o recebimento será gerado por padrão nas novas locações. Você pode alterar em cada locação individualmente."
    const val MOMENTO_PAGAMENTO_SALVAR = "Salvar Preferência"
    const val MOMENTO_PAGAMENTO_SUCESSO = "Preferência salva com sucesso!"
    const val MOMENTO_PAGAMENTO_ERRO = "Erro ao salvar preferência"

    // Feedback Screen
    const val MENU_FEEDBACK = "Deixe seu Feedback"
    const val MENU_FEEDBACK_SUBTITLE = "Envie sugestões ou reporte problemas"
    const val FEEDBACK_TITLE = "Deixe seu Feedback"
    const val FEEDBACK_SUBTITLE = "Sua opinião é importante para nós"
    const val FEEDBACK_MOTIVO = "Qual o motivo do seu feedback?"
    const val FEEDBACK_MOTIVO_SUGESTAO = "Sugestão"
    const val FEEDBACK_MOTIVO_BUG = "Reportar Bug"
    const val FEEDBACK_MOTIVO_RECLAMACAO = "Reclamação"
    const val FEEDBACK_MOTIVO_DUVIDA = "Dúvida"
    const val FEEDBACK_MOTIVO_ELOGIO = "Elogio"
    const val FEEDBACK_MOTIVO_OUTRO = "Outro"
    const val FEEDBACK_MENSAGEM = "Sua mensagem"
    const val FEEDBACK_MENSAGEM_PLACEHOLDER = "Descreva sua sugestão, problema ou dúvida..."
    const val FEEDBACK_ENVIAR = "Enviar Feedback"
    const val FEEDBACK_SUCESSO = "Feedback enviado com sucesso! Obrigado."
    const val FEEDBACK_ERRO = "Erro ao enviar feedback"
    const val FEEDBACK_ERRO_MOTIVO = "Selecione um motivo"
    const val FEEDBACK_ERRO_MENSAGEM = "Digite sua mensagem"

    // Notifications Screen
    const val NOTIFICATIONS_TITLE = "Notificações"
    const val NOTIFICATIONS_SUBTITLE = "Suas notificações recentes"
    const val NOTIFICATIONS_EMPTY_TITLE = "Nenhuma notificação"
    const val NOTIFICATIONS_EMPTY_SUBTITLE = "Você não tem notificações no momento"
    const val NOTIFICATIONS_MARCAR_LIDA = "Marcar como lida"
    const val NOTIFICATIONS_MARCAR_TODAS_LIDAS = "Marcar todas como lidas"
    const val NOTIFICATIONS_EXCLUIR = "Excluir"
    const val NOTIFICATIONS_LIMPAR_LIDAS = "Limpar lidas"
    const val NOTIFICATIONS_HOJE = "Hoje"
    const val NOTIFICATIONS_ONTEM = "Ontem"
    const val NOTIFICATIONS_ESTA_SEMANA = "Esta semana"
    const val NOTIFICATIONS_ANTERIORES = "Anteriores"

    // Data and Privacy Screen
    const val DATA_PRIVACY_TITLE = "Dados e Privacidade"
    const val DATA_PRIVACY_SUBTITLE = "Gerencie seus dados e privacidade"
    const val DATA_PRIVACY_SECTION_LEGAL = "Legal"
    const val DATA_PRIVACY_SECTION_DANGER = "Zona de Perigo"
    const val DATA_PRIVACY_TERMOS_USO = "Termos de Uso"
    const val DATA_PRIVACY_TERMOS_USO_SUBTITLE = "Leia nossos termos de uso"
    const val DATA_PRIVACY_POLITICA = "Política de Privacidade"
    const val DATA_PRIVACY_POLITICA_SUBTITLE = "Saiba como tratamos seus dados"
    const val DATA_PRIVACY_EXCLUIR_CONTA = "Excluir Conta"
    const val DATA_PRIVACY_EXCLUIR_CONTA_SUBTITLE = "Apagar permanentemente sua conta"
    const val DATA_PRIVACY_EXCLUIR_TITULO = "Excluir Conta"
    const val DATA_PRIVACY_EXCLUIR_MENSAGEM = "Tem certeza que deseja excluir sua conta? Esta ação é irreversível e todos os seus dados serão apagados permanentemente."
    const val DATA_PRIVACY_DIGITE_SENHA = "Digite sua senha"
    const val DATA_PRIVACY_EXCLUINDO = "Excluindo conta..."
    const val DATA_PRIVACY_ERRO_EXCLUIR = "Erro ao excluir conta"

    // Change Password Screen
    const val CHANGE_PASSWORD_TITLE = "Alterar Senha"
    const val CHANGE_PASSWORD_SUBTITLE = "Atualize sua senha de acesso"
    const val CHANGE_PASSWORD_SENHA_ATUAL = "Senha Atual"
    const val CHANGE_PASSWORD_SENHA_ATUAL_PLACEHOLDER = "Digite sua senha atual"
    const val CHANGE_PASSWORD_NOVA_SENHA = "Nova Senha"
    const val CHANGE_PASSWORD_NOVA_SENHA_PLACEHOLDER = "Digite a nova senha"
    const val CHANGE_PASSWORD_CONFIRMAR_SENHA = "Confirmar Nova Senha"
    const val CHANGE_PASSWORD_CONFIRMAR_PLACEHOLDER = "Confirme a nova senha"
    const val CHANGE_PASSWORD_BOTAO = "Alterar Senha"

    // Change Email Screen
    const val CHANGE_EMAIL_TITLE = "Alterar Email"
    const val CHANGE_EMAIL_SUBTITLE = "Atualize seu email de acesso"
    const val CHANGE_EMAIL_ATUAL = "Email Atual"
    const val CHANGE_EMAIL_NOVO = "Novo Email"
    const val CHANGE_EMAIL_NOVO_PLACEHOLDER = "Digite o novo email"
    const val CHANGE_EMAIL_SENHA_CONFIRMAR = "Senha para Confirmar"
    const val CHANGE_EMAIL_SENHA_PLACEHOLDER = "Digite sua senha"
    const val CHANGE_EMAIL_BOTAO = "Alterar Email"

    // Auth - Login Screen
    const val LOGIN_TITLE = "Entrar"
    const val LOGIN_EMAIL_LABEL = "Email"
    const val LOGIN_EMAIL_PLACEHOLDER = "seu@email.com"
    const val LOGIN_EMAIL_INVALIDO = "Email inválido"
    const val LOGIN_SENHA_LABEL = "Senha"
    const val LOGIN_SENHA_PLACEHOLDER = "Sua senha"
    const val LOGIN_MOSTRAR_SENHA = "Mostrar senha"
    const val LOGIN_ESCONDER_SENHA = "Esconder senha"
    const val LOGIN_ESQUECEU_SENHA = "Esqueceu a senha?"
    const val LOGIN_BOTAO = "Entrar"
    const val LOGIN_SEM_CONTA = "Não tem uma conta?"
    const val LOGIN_CADASTRESE = "Cadastre-se"
    const val LOGIN_RECUPERAR_SENHA_TITLE = "Recuperar Senha"
    const val LOGIN_RECUPERAR_SENHA_DESC = "Digite seu email para receber um link de recuperação de senha."
    const val LOGIN_ENVIAR = "Enviar"

    // Auth - Register Screen
    const val REGISTER_TITLE = "Criar Conta"
    const val REGISTER_NOME_LABEL = "Nome"
    const val REGISTER_NOME_PLACEHOLDER = "Seu nome completo"
    const val REGISTER_SENHA_PLACEHOLDER = "Mínimo 6 caracteres"
    const val REGISTER_CONFIRMAR_SENHA_LABEL = "Confirmar Senha"
    const val REGISTER_CONFIRMAR_SENHA_PLACEHOLDER = "Repita a senha"
    const val REGISTER_SENHAS_NAO_COINCIDEM = "As senhas não coincidem"
    const val REGISTER_SENHA_MINIMO = "A senha deve ter pelo menos 6 caracteres"
    const val REGISTER_BOTAO = "Criar Conta"
    const val REGISTER_JA_TEM_CONTA = "Já tem uma conta?"

    // Auth - Validation Messages
    const val AUTH_PREENCHA_EMAIL_SENHA = "Preencha email e senha"
    const val AUTH_DIGITE_NOME = "Digite seu nome"
    const val AUTH_DIGITE_EMAIL = "Digite seu email"
    const val AUTH_ERRO_LOGIN = "Erro ao fazer login"
    const val AUTH_ERRO_CRIAR_CONTA = "Erro ao criar conta"
    const val AUTH_ERRO_ENVIAR_EMAIL = "Erro ao enviar email"
    fun authEmailRecuperacaoEnviado(email: String) = "Email de recuperação enviado para $email"

    // Locacoes Screen
    const val LOCACOES_TITLE = "Locações"
    const val LOCACOES_TAB_ATIVOS = "Ativos"
    const val LOCACOES_TAB_FINALIZADOS = "Finalizados"
    const val LOCACOES_ATIVA_SINGULAR = "locação ativa"
    const val LOCACOES_ATIVA_PLURAL = "locações ativas"
    const val LOCACOES_FINALIZADA_SINGULAR = "locação finalizada"
    const val LOCACOES_FINALIZADA_PLURAL = "locações finalizadas"
    const val LOCACOES_EMPTY_ATIVAS_TITLE = "Nenhuma locação ativa"
    const val LOCACOES_EMPTY_ATIVAS_SUBTITLE = "Clique no botão Locar para criar sua primeira locação"
    const val LOCACOES_EMPTY_FINALIZADAS_TITLE = "Nenhuma locação finalizada"
    const val LOCACOES_EMPTY_FINALIZADAS_SUBTITLE = "As locações concluídas aparecerão aqui"
    const val LOCACOES_EXCLUIR_TITULO = "Excluir Locação"
    const val LOCACOES_EXCLUIR_MENSAGEM = "Tem certeza que deseja excluir esta locação? Esta ação não pode ser desfeita."
    const val LOCACOES_EXCLUIDA_SUCESSO = "Locação excluída com sucesso!"

    // Nova Locacao Screen
    const val NOVA_LOCACAO_TITLE = "Nova Locação"
    const val NOVA_LOCACAO_CLIENTE = "Cliente"
    const val NOVA_LOCACAO_SELECIONAR_CLIENTE = "Selecionar cliente"
    const val NOVA_LOCACAO_EQUIPAMENTO = "Equipamento"
    const val NOVA_LOCACAO_SELECIONAR_EQUIPAMENTO = "Selecionar equipamento"
    const val NOVA_LOCACAO_VALOR = "Valor da Locação"
    const val NOVA_LOCACAO_VALOR_PLACEHOLDER = "R$ 0,00"
    const val NOVA_LOCACAO_DATA_INICIO = "Data Inicio"
    const val NOVA_LOCACAO_DATA_FIM = "Data Fim Prevista"
    const val NOVA_LOCACAO_DATA_VENCIMENTO = "Vencimento do Pagamento"
    const val NOVA_LOCACAO_SELECIONAR_DATA = "Selecionar data"
    const val NOVA_LOCACAO_STATUS_ENTREGA = "Status de Entrega"
    const val NOVA_LOCACAO_DATA_ENTREGA = "Data de Entrega Prevista"
    const val NOVA_LOCACAO_EMITIR_NOTA = "Emitir Nota Fiscal"
    const val NOVA_LOCACAO_EMITIR_NOTA_SUBTITLE = "Cliente será notificado sobre a NF"
    const val NOVA_LOCACAO_CRIAR = "Criar Locação"
    const val NOVA_LOCACAO_NENHUM_CLIENTE = "Nenhum cliente cadastrado"
    const val NOVA_LOCACAO_NENHUM_EQUIPAMENTO = "Nenhum equipamento disponível"
    const val NOVA_LOCACAO_EQUIPAMENTOS_ALUGADOS = "Todos estão alugados ou nenhum foi cadastrado"
    const val NOVA_LOCACAO_DESCARTAR_TITULO = "Descartar alterações?"
    const val NOVA_LOCACAO_DESCARTAR_MENSAGEM = "Os dados preenchidos serão perdidos. Deseja continuar?"
    const val NOVA_LOCACAO_DESCARTAR = "Descartar"

    // Selecionar Cliente Screen
    const val SELECIONAR_CLIENTE_TITLE = "Selecionar Cliente"
    const val SELECIONAR_CLIENTE_BUSCAR = "Buscar por nome ou CPF/CNPJ"
    const val SELECIONAR_CLIENTE_LIMPAR = "Limpar"
    const val SELECIONAR_CLIENTE_NENHUM_ENCONTRADO = "Nenhum cliente encontrado"
    const val SELECIONAR_CLIENTE_NENHUM_CADASTRADO = "Nenhum cliente cadastrado"
    const val SELECIONAR_CLIENTE_TENTE_OUTROS_TERMOS = "Tente buscar com outros termos ou adicione um novo cliente"
    const val SELECIONAR_CLIENTE_ADICIONE_PRIMEIRO = "Adicione seu primeiro cliente"
    const val SELECIONAR_CLIENTE_ADICIONAR = "Adicionar Cliente"

    // Selecionar Equipamento Screen
    const val SELECIONAR_EQUIPAMENTO_TITLE = "Selecionar Equipamento"
    const val SELECIONAR_EQUIPAMENTO_BUSCAR = "Buscar por nome ou tipo"
    const val SELECIONAR_EQUIPAMENTO_LIMPAR = "Limpar"
    const val SELECIONAR_EQUIPAMENTO_INFO = "Mostrando apenas equipamentos disponíveis para locação"
    const val SELECIONAR_EQUIPAMENTO_NENHUM_ENCONTRADO = "Nenhum equipamento encontrado"
    const val SELECIONAR_EQUIPAMENTO_NENHUM_DISPONIVEL = "Nenhum equipamento disponível"
    const val SELECIONAR_EQUIPAMENTO_TENTE_OUTROS_TERMOS = "Tente buscar com outros termos ou adicione um novo equipamento"
    const val SELECIONAR_EQUIPAMENTO_TODOS_ALUGADOS = "Todos os equipamentos estão alugados ou você ainda não cadastrou nenhum"
    const val SELECIONAR_EQUIPAMENTO_ADICIONAR = "Adicionar Equipamento"
    const val SELECIONAR_EQUIPAMENTO_POR_DIA = "/dia"

    // Status Entrega
    const val STATUS_ENTREGA_NAO_AGENDADA = "Não Agendada"
    const val STATUS_ENTREGA_AGENDADA = "Agendada"
    const val STATUS_ENTREGA_ENTREGUE = "Entregue"

    // Status Pagamento
    const val STATUS_PAGAMENTO_PENDENTE = "Pendente"
    const val STATUS_PAGAMENTO_PAGO = "Pago"

    // Status Coleta
    const val STATUS_COLETA_NAO_COLETADO = "Não Coletado"
    const val STATUS_COLETA_COLETADO = "Coletado"

    // Status Prazo
    const val STATUS_PRAZO_NORMAL = "Normal"
    const val STATUS_PRAZO_PROXIMO = "Próx. Vencimento"
    const val STATUS_PRAZO_VENCIDO = "Vencido"

    // Status Locacao
    const val STATUS_LOCACAO_ATIVA = "Ativa"
    const val STATUS_LOCACAO_FINALIZADA = "Finalizada"
    const val STATUS_LOCACAO_VENCIDA = "Vencida"
    const val STATUS_LOCACAO_PROXIMO_VENCIMENTO = "Próximo do Vencimento"

    // Detalhes Locacao Screen
    const val DETALHES_TITLE = "Detalhes da Locação"
    const val DETALHES_VOLTAR = "Voltar"
    const val DETALHES_STATUS = "Status da Locação"
    const val DETALHES_CLIENTE = "Cliente"
    const val DETALHES_EQUIPAMENTO = "Equipamento"
    const val DETALHES_INFO_LOCACAO = "Informações da Locação"
    const val DETALHES_VALOR = "Valor"
    const val DETALHES_PERIODO = "Período"
    const val DETALHES_DATA_INICIO = "Data Início"
    const val DETALHES_DATA_FIM = "Data Fim Prevista"
    const val DETALHES_RENOVACOES = "Renovações"
    const val DETALHES_PAGAMENTO = "Pagamento"
    const val DETALHES_ENTREGA = "Entrega"
    const val DETALHES_COLETA = "Coleta"
    const val DETALHES_NOTA_FISCAL = "Nota Fiscal"
    const val DETALHES_MARCAR_PAGO = "Marcar como Pago"
    const val DETALHES_MARCAR_ENTREGUE = "Marcar como Entregue"
    const val DETALHES_MARCAR_COLETADO = "Marcar como Coletado"
    const val DETALHES_MARCAR_NOTA_EMITIDA = "Marcar como Emitida"
    const val DETALHES_RENOVAR = "Renovar Locação"
    const val DETALHES_NOTA_EMITIDA = "Emitida"
    const val DETALHES_GERAR_RECIBO = "Gerar Recibo"
    const val DETALHES_VER_RECEBIMENTOS = "Ver Recebimentos"

    // Renovar Dialog
    const val RENOVAR_TITLE = "Renovar Locação"
    const val RENOVAR_NOVA_DATA = "Nova Data de Fim"
    const val RENOVAR_MANTER_VALOR = "Manter valor atual"
    const val RENOVAR_NOVO_VALOR = "Novo Valor"

    // Entregas Screen
    const val ENTREGAS_TITLE = "Entregas"
    const val ENTREGAS_PENDENTE_SINGULAR = "entrega pendente"
    const val ENTREGAS_PENDENTE_PLURAL = "entregas pendentes"
    const val ENTREGAS_EMPTY_TITLE = "Nenhuma entrega pendente"
    const val ENTREGAS_EMPTY_SUBTITLE = "Locações com entrega agendada ou pendente aparecerão aqui"
    const val ENTREGAS_CONFIRMAR = "Confirmar Entrega"
    const val ENTREGAS_VENCIMENTO = "Vencimento"

    // Recebimentos Screen
    const val RECEBIMENTOS_TITLE = "Recebimentos"
    const val RECEBIMENTOS_TAB_PENDENTES = "Pendentes"
    const val RECEBIMENTOS_TAB_PAGOS = "Pagos"
    const val RECEBIMENTOS_PENDENTE_SINGULAR = "pagamento pendente"
    const val RECEBIMENTOS_PENDENTE_PLURAL = "pagamentos pendentes"
    const val RECEBIMENTOS_PAGO_SINGULAR = "pagamento recebido"
    const val RECEBIMENTOS_PAGO_PLURAL = "pagamentos recebidos"
    const val LOCACAO_PAGA_SINGULAR = "locação paga"
    const val LOCACAO_PAGA_PLURAL = "locações pagas"
    const val RECEBIMENTOS_TOTAL = "Total a receber"
    const val RECEBIMENTOS_TOTAL_PAGO = "Total recebido"
    const val RECEBIMENTOS_EMPTY_TITLE = "Nenhum recebimento pendente"
    const val RECEBIMENTOS_EMPTY_SUBTITLE = "Locações com equipamentos coletados e pagamento pendente aparecerão aqui"
    const val RECEBIMENTOS_EMPTY_PAGOS_TITLE = "Nenhum pagamento recebido"
    const val RECEBIMENTOS_EMPTY_PAGOS_SUBTITLE = "Os pagamentos confirmados aparecerão aqui"
    const val RECEBIMENTOS_CONFIRMAR = "Confirmar Recebimento"
    const val RECEBIMENTOS_VALOR = "Valor a receber"
    const val RECEBIMENTOS_VALOR_PAGO = "Valor pago"
    const val RECEBIMENTOS_PERIODO = "Período"
    const val RECEBIMENTOS_STATUS = "Status"
    const val RECEBIMENTOS_DATA_PAGAMENTO = "Data do Pagamento"
    const val RECEBIMENTOS_VENCIMENTO = "Vencimento"
    const val RECEBIMENTOS_RENOVACAO = "Renovação"
    const val RECEBIMENTOS_LOCACAO_SUBTITLE = "Recebimento desta locação"
    const val RECEBIMENTO_CONFIRMADO = "Recebimento confirmado!"
    const val RECEBIMENTOS_FILTRO_MES = "Filtrar por mês"
    const val RECEBIMENTOS_TODOS_MESES = "Todos os meses"

    // Meses do ano
    val MESES = listOf(
        "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho",
        "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"
    )
    fun formatMesAno(mes: Int, ano: Int) = "${MESES[mes - 1]}/$ano"

    // Clientes Screen
    const val CLIENTES_TITLE = "Clientes"
    const val CLIENTES_NOVO = "Novo"
    const val CLIENTES_BUSCAR = "Buscar cliente..."
    const val CLIENTES_EMPTY_TITLE = "Nenhum cliente cadastrado"
    const val CLIENTES_EMPTY_SUBTITLE = "Cadastre um novo cliente para começar"
    const val CLIENTES_EMPTY_SEARCH_TITLE = "Nenhum cliente encontrado"
    const val CLIENTES_EMPTY_SEARCH_SUBTITLE = "Tente buscar por outro termo"
    const val CLIENTES_CADASTRAR = "Cadastrar Cliente"
    const val CLIENTES_EDITAR = "Editar"
    const val CLIENTES_EXCLUIR = "Excluir"

    // Cliente Form
    const val CLIENTE_FORM_NOVO = "Novo Cliente"
    const val CLIENTE_FORM_EDITAR = "Editar Cliente"
    const val CLIENTE_FORM_NOME = "Nome / Razão Social *"
    const val CLIENTE_FORM_NOME_PLACEHOLDER = "Nome completo ou razão social"
    const val CLIENTE_FORM_CPF_CNPJ = "CPF / CNPJ"
    const val CLIENTE_FORM_CPF_CNPJ_PLACEHOLDER = "000.000.000-00"
    const val CLIENTE_FORM_TELEFONE = "Telefone / WhatsApp *"
    const val CLIENTE_FORM_TELEFONE_PLACEHOLDER = "(00) 00000-0000"
    const val CLIENTE_FORM_EMAIL = "E-mail"
    const val CLIENTE_FORM_EMAIL_PLACEHOLDER = "email@exemplo.com"
    const val CLIENTE_FORM_ENDERECO = "Endereço"
    const val CLIENTE_FORM_ENDERECO_PLACEHOLDER = "Endereço completo"
    const val CLIENTE_FORM_NOTA_FISCAL = "Precisa de Nota Fiscal"
    const val CLIENTE_FORM_CADASTRAR = "Cadastrar"
    const val CLIENTE_FORM_ATUALIZAR = "Atualizar"

    // Equipamentos Screen
    const val EQUIPAMENTOS_TITLE = "Equipamentos"
    const val EQUIPAMENTOS_NOVO = "Novo"
    const val EQUIPAMENTOS_BUSCAR = "Buscar equipamento..."
    const val EQUIPAMENTOS_EMPTY_TITLE = "Nenhum equipamento cadastrado"
    const val EQUIPAMENTOS_EMPTY_SUBTITLE = "Cadastre um novo equipamento para começar"
    const val EQUIPAMENTOS_EMPTY_SEARCH_TITLE = "Nenhum equipamento encontrado"
    const val EQUIPAMENTOS_EMPTY_SEARCH_SUBTITLE = "Tente buscar por outro termo"
    const val EQUIPAMENTOS_CADASTRAR = "Cadastrar Equipamento"
    const val EQUIPAMENTOS_EDITAR = "Editar"
    const val EQUIPAMENTOS_EXCLUIR = "Excluir"
    const val EQUIPAMENTOS_ALUGADO = "Alugado"
    const val EQUIPAMENTOS_DISPONIVEL = "Disponível"
    const val EQUIPAMENTOS_PRECO_LOCACAO = "Preço locação"
    const val EQUIPAMENTOS_VALOR_COMPRA = "Valor de compra"

    // Equipamento Form
    const val EQUIPAMENTO_FORM_NOVO = "Novo Equipamento"
    const val EQUIPAMENTO_FORM_EDITAR = "Editar Equipamento"
    const val EQUIPAMENTO_FORM_NOME = "Nome do Equipamento *"
    const val EQUIPAMENTO_FORM_NOME_PLACEHOLDER = "Ex: Betoneira 400L"
    const val EQUIPAMENTO_FORM_CATEGORIA = "Categoria *"
    const val EQUIPAMENTO_FORM_CATEGORIA_PLACEHOLDER = "Ex: Betoneira, Martelete, Escora"
    const val EQUIPAMENTO_FORM_IDENTIFICACAO = "Identificação / Patrimônio"
    const val EQUIPAMENTO_FORM_IDENTIFICACAO_PLACEHOLDER = "Ex: #001, PAT-123"
    const val EQUIPAMENTO_FORM_PRECO = "Preço Padrão de Locação *"
    const val EQUIPAMENTO_FORM_PRECO_PLACEHOLDER = "0.00"
    const val EQUIPAMENTO_FORM_VALOR_COMPRA = "Valor de Compra"
    const val EQUIPAMENTO_FORM_VALOR_COMPRA_PLACEHOLDER = "0.00"
    const val EQUIPAMENTO_FORM_OBSERVACOES = "Observações"
    const val EQUIPAMENTO_FORM_OBSERVACOES_PLACEHOLDER = "Informações adicionais sobre o equipamento"
    const val EQUIPAMENTO_FORM_CADASTRAR = "Cadastrar"
    const val EQUIPAMENTO_FORM_ATUALIZAR = "Atualizar"
    const val EQUIPAMENTO_FORM_PRECOS_TITLE = "Preços por Período *"
    const val EQUIPAMENTO_FORM_PRECOS_SUBTITLE = "Informe pelo menos um preço"
    const val EQUIPAMENTO_FORM_PRECO_DIARIO = "Preço Diário"
    const val EQUIPAMENTO_FORM_PRECO_SEMANAL = "Preço Semanal (7 dias)"
    const val EQUIPAMENTO_FORM_PRECO_QUINZENAL = "Preço Quinzenal (15 dias)"
    const val EQUIPAMENTO_FORM_PRECO_MENSAL = "Preço Mensal (30 dias)"

    // Períodos
    const val PERIODO_DIARIO = "Diário"
    const val PERIODO_SEMANAL = "Semanal"
    const val PERIODO_QUINZENAL = "Quinzenal"
    const val PERIODO_MENSAL = "Mensal"
    const val NOVA_LOCACAO_PERIODO = "Período"

    // Currency
    const val CURRENCY_SYMBOL = "R$"

    // Common
    const val COMMON_VOLTAR = "Voltar"
    const val COMMON_FECHAR = "Fechar"
    const val COMMON_CANCELAR = "Cancelar"
    const val COMMON_CONFIRMAR = "Confirmar"
    const val COMMON_SALVAR = "Salvar"
    const val COMMON_EDITAR = "Editar"
    const val COMMON_EXCLUIR = "Excluir"
    const val COMMON_ERRO = "Erro"
    const val COMMON_SUCESSO = "Sucesso"
    const val COMMON_CARREGANDO = "Carregando..."
    const val COMMON_CLIENTE_NAO_ENCONTRADO = "Cliente não encontrado"
    const val COMMON_EQUIPAMENTO_NAO_ENCONTRADO = "Equipamento não encontrado"
    const val COMMON_ERRO_DESCONHECIDO = "Erro desconhecido"

    // Validation Messages
    const val VALIDATION_SELECIONE_CLIENTE = "Selecione um cliente"
    const val VALIDATION_SELECIONE_EQUIPAMENTO = "Selecione um equipamento"
    const val VALIDATION_SELECIONE_PERIODO = "Selecione o período de locação"
    const val VALIDATION_PELO_MENOS_UM_PRECO = "Informe pelo menos um preço de locação"
    const val VALIDATION_INFORME_DATA_FIM = "Informe a data de fim prevista"
    const val VALIDATION_INFORME_VALOR = "Informe um valor válido"
    const val VALIDATION_INFORME_DATA_ENTREGA = "Informe a data de entrega prevista"
    const val VALIDATION_SELECIONE_MOMENTO_PAGAMENTO = "Selecione o momento do pagamento"

    // Success Messages
    const val SUCCESS_LOCACAO_CRIADA = "Locação criada com sucesso!"
    const val SUCCESS_LOCACAO_RENOVADA = "Locação renovada com sucesso!"
    const val SUCCESS_PAGAMENTO_MARCADO = "Pagamento marcado como pago!"
    const val SUCCESS_ENTREGA_MARCADA = "Equipamento marcado como entregue!"
    const val SUCCESS_COLETA_MARCADA = "Equipamento marcado como coletado!"
    const val SUCCESS_NOTA_EMITIDA = "Nota fiscal marcada como emitida!"
    const val SUCCESS_CLIENTE_SALVO = "Cliente salvo com sucesso!"
    const val SUCCESS_CLIENTE_EXCLUIDO = "Cliente excluído com sucesso!"
    const val SUCCESS_EQUIPAMENTO_SALVO = "Equipamento salvo com sucesso!"
    const val SUCCESS_EQUIPAMENTO_EXCLUIDO = "Equipamento excluído com sucesso!"

    // Error Messages
    const val ERROR_LOCACAO_NAO_ENCONTRADA = "Locação não encontrada"
    const val ERROR_CRIAR_LOCACAO = "Erro ao criar locação"
    const val ERROR_RENOVAR_LOCACAO = "Erro ao renovar locação"
    const val ERROR_MARCAR_PAGAMENTO = "Erro ao marcar pagamento"
    const val ERROR_MARCAR_ENTREGA = "Erro ao marcar entrega"
    const val ERROR_MARCAR_COLETA = "Erro ao marcar coleta"
    const val ERROR_MARCAR_NOTA = "Erro ao marcar nota"
    const val ERROR_SALVAR_CLIENTE = "Erro ao salvar cliente"
    const val ERROR_EXCLUIR_CLIENTE = "Erro ao excluir cliente"
    const val ERROR_SALVAR_EQUIPAMENTO = "Erro ao salvar equipamento"
    const val ERROR_EXCLUIR_EQUIPAMENTO = "Erro ao excluir equipamento"

    // Helper functions for pluralization
    fun locacoesAtivas(count: Int) = "$count ${if (count == 1) LOCACOES_ATIVA_SINGULAR else LOCACOES_ATIVA_PLURAL}"
    fun locacoesFinalizadas(count: Int) = "$count ${if (count == 1) LOCACOES_FINALIZADA_SINGULAR else LOCACOES_FINALIZADA_PLURAL}"
    fun entregasPendentes(count: Int) = "$count ${if (count == 1) ENTREGAS_PENDENTE_SINGULAR else ENTREGAS_PENDENTE_PLURAL}"
    fun recebimentosPendentes(count: Int) = "$count ${if (count == 1) RECEBIMENTOS_PENDENTE_SINGULAR else RECEBIMENTOS_PENDENTE_PLURAL}"
    fun recebimentosPagos(count: Int) = "$count ${if (count == 1) RECEBIMENTOS_PAGO_SINGULAR else RECEBIMENTOS_PAGO_PLURAL}"
    fun locacoesPagas(count: Int) = "$count ${if (count == 1) LOCACAO_PAGA_SINGULAR else LOCACAO_PAGA_PLURAL}"
    fun clientesCadastrados(count: Int) = "$count ${if (count == 1) "cliente cadastrado" else "clientes cadastrados"}"
    fun equipamentosCadastrados(count: Int) = "$count ${if (count == 1) "equipamento cadastrado" else "equipamentos cadastrados"}"
    fun formatId(id: String) = "ID: $id"
    fun formatPrevista(data: String) = "Prevista: $data"
    fun formatDataPrevista(data: String) = "Data prevista: $data"
    fun formatPrecoPeriodo(periodo: String) = "Preço ${periodo.lowercase()}"
    fun formatPeriodoSufixo(periodo: String) = "/${periodo.lowercase()}"
    fun formatOutrosPeriodos(count: Int) = "+$count ${if (count == 1) "outro" else "outros"}"
}
