package br.com.codecacto.locadora.core.ui.strings

object Strings {
    // App
    const val APP_NAME = "Locadora"
    const val APP_VERSION = "Versão 1.0.0"
    const val APP_DESCRIPTION = "Controle de Locações"

    // Navigation
    const val NAV_LOCACOES = "Locações"
    const val NAV_ENTREGAS = "Entregas"
    const val NAV_RECEBER = "Receber"
    const val NAV_MENU = "Menu"
    const val NAV_LOCAR = "Locar"

    // Menu Screen
    const val MENU_TITLE = "Menu"
    const val MENU_SUBTITLE = "Configurações e cadastros"
    const val MENU_CLIENTES = "Clientes"
    const val MENU_CLIENTES_SUBTITLE = "Gerenciar clientes"
    const val MENU_EQUIPAMENTOS = "Equipamentos"
    const val MENU_EQUIPAMENTOS_SUBTITLE = "Gerenciar equipamentos"
    const val MENU_SAIR = "Sair"
    const val MENU_SAIR_SUBTITLE = "Encerrar sessão"

    // Auth - Login Screen
    const val LOGIN_TITLE = "Entrar"
    const val LOGIN_EMAIL_LABEL = "Email"
    const val LOGIN_EMAIL_PLACEHOLDER = "seu@email.com"
    const val LOGIN_EMAIL_INVALIDO = "Email inválido"
    const val LOGIN_SENHA_LABEL = "Senha"
    const val LOGIN_SENHA_PLACEHOLDER = "Sua senha"
    const val LOGIN_MOSTRAR_SENHA = "Mostrar senha"
    const val LOGIN_ESCONDER_SENHA = "Esconder senha"
    const val LOGIN_ESQUECEU_SENHA = "Esqueceu a senha?"
    const val LOGIN_BOTAO = "Entrar"
    const val LOGIN_SEM_CONTA = "Não tem uma conta?"
    const val LOGIN_CADASTRESE = "Cadastre-se"
    const val LOGIN_RECUPERAR_SENHA_TITLE = "Recuperar Senha"
    const val LOGIN_RECUPERAR_SENHA_DESC = "Digite seu email para receber um link de recuperação de senha."
    const val LOGIN_ENVIAR = "Enviar"

    // Auth - Register Screen
    const val REGISTER_TITLE = "Criar Conta"
    const val REGISTER_NOME_LABEL = "Nome"
    const val REGISTER_NOME_PLACEHOLDER = "Seu nome completo"
    const val REGISTER_SENHA_PLACEHOLDER = "Mínimo 6 caracteres"
    const val REGISTER_CONFIRMAR_SENHA_LABEL = "Confirmar Senha"
    const val REGISTER_CONFIRMAR_SENHA_PLACEHOLDER = "Repita a senha"
    const val REGISTER_SENHAS_NAO_COINCIDEM = "As senhas não coincidem"
    const val REGISTER_SENHA_MINIMO = "A senha deve ter pelo menos 6 caracteres"
    const val REGISTER_BOTAO = "Criar Conta"
    const val REGISTER_JA_TEM_CONTA = "Já tem uma conta?"

    // Auth - Validation Messages
    const val AUTH_PREENCHA_EMAIL_SENHA = "Preencha email e senha"
    const val AUTH_DIGITE_NOME = "Digite seu nome"
    const val AUTH_DIGITE_EMAIL = "Digite seu email"
    const val AUTH_ERRO_LOGIN = "Erro ao fazer login"
    const val AUTH_ERRO_CRIAR_CONTA = "Erro ao criar conta"
    const val AUTH_ERRO_ENVIAR_EMAIL = "Erro ao enviar email"
    fun authEmailRecuperacaoEnviado(email: String) = "Email de recuperação enviado para $email"

    // Locacoes Screen
    const val LOCACOES_TITLE = "Locações"
    const val LOCACOES_TAB_ATIVOS = "Ativos"
    const val LOCACOES_TAB_FINALIZADOS = "Finalizados"
    const val LOCACOES_ATIVA_SINGULAR = "locação ativa"
    const val LOCACOES_ATIVA_PLURAL = "locações ativas"
    const val LOCACOES_FINALIZADA_SINGULAR = "locação finalizada"
    const val LOCACOES_FINALIZADA_PLURAL = "locações finalizadas"
    const val LOCACOES_EMPTY_ATIVAS_TITLE = "Nenhuma locação ativa"
    const val LOCACOES_EMPTY_ATIVAS_SUBTITLE = "Clique no botão Locar para criar sua primeira locação"
    const val LOCACOES_EMPTY_FINALIZADAS_TITLE = "Nenhuma locação finalizada"
    const val LOCACOES_EMPTY_FINALIZADAS_SUBTITLE = "As locações concluídas aparecerão aqui"

    // Nova Locacao Screen
    const val NOVA_LOCACAO_TITLE = "Nova Locação"
    const val NOVA_LOCACAO_CLIENTE = "Cliente"
    const val NOVA_LOCACAO_SELECIONAR_CLIENTE = "Selecionar cliente"
    const val NOVA_LOCACAO_EQUIPAMENTO = "Equipamento"
    const val NOVA_LOCACAO_SELECIONAR_EQUIPAMENTO = "Selecionar equipamento"
    const val NOVA_LOCACAO_VALOR = "Valor da Locação"
    const val NOVA_LOCACAO_VALOR_PLACEHOLDER = "R$ 0,00"
    const val NOVA_LOCACAO_DATA_INICIO = "Data Início"
    const val NOVA_LOCACAO_DATA_FIM = "Data Fim Prevista"
    const val NOVA_LOCACAO_SELECIONAR_DATA = "Selecionar data"
    const val NOVA_LOCACAO_STATUS_ENTREGA = "Status de Entrega"
    const val NOVA_LOCACAO_DATA_ENTREGA = "Data de Entrega Prevista"
    const val NOVA_LOCACAO_EMITIR_NOTA = "Emitir Nota Fiscal"
    const val NOVA_LOCACAO_EMITIR_NOTA_SUBTITLE = "Cliente será notificado sobre a NF"
    const val NOVA_LOCACAO_CRIAR = "Criar Locação"
    const val NOVA_LOCACAO_NENHUM_CLIENTE = "Nenhum cliente cadastrado"
    const val NOVA_LOCACAO_NENHUM_EQUIPAMENTO = "Nenhum equipamento disponível"
    const val NOVA_LOCACAO_EQUIPAMENTOS_ALUGADOS = "Todos estão alugados ou nenhum foi cadastrado"

    // Status Entrega
    const val STATUS_ENTREGA_NAO_AGENDADA = "Não Agendada"
    const val STATUS_ENTREGA_AGENDADA = "Agendada"
    const val STATUS_ENTREGA_ENTREGUE = "Entregue"

    // Status Pagamento
    const val STATUS_PAGAMENTO_PENDENTE = "Pendente"
    const val STATUS_PAGAMENTO_PAGO = "Pago"

    // Status Coleta
    const val STATUS_COLETA_NAO_COLETADO = "Não Coletado"
    const val STATUS_COLETA_COLETADO = "Coletado"

    // Status Prazo
    const val STATUS_PRAZO_NORMAL = "Normal"
    const val STATUS_PRAZO_PROXIMO = "Próx. Vencimento"
    const val STATUS_PRAZO_VENCIDO = "Vencido"

    // Status Locacao
    const val STATUS_LOCACAO_ATIVA = "Ativa"
    const val STATUS_LOCACAO_FINALIZADA = "Finalizada"
    const val STATUS_LOCACAO_VENCIDA = "Vencida"
    const val STATUS_LOCACAO_PROXIMO_VENCIMENTO = "Próximo do Vencimento"

    // Detalhes Locacao Screen
    const val DETALHES_TITLE = "Detalhes da Locação"
    const val DETALHES_VOLTAR = "Voltar"
    const val DETALHES_STATUS = "Status da Locação"
    const val DETALHES_CLIENTE = "Cliente"
    const val DETALHES_EQUIPAMENTO = "Equipamento"
    const val DETALHES_INFO_LOCACAO = "Informações da Locação"
    const val DETALHES_VALOR = "Valor"
    const val DETALHES_DATA_INICIO = "Data Início"
    const val DETALHES_DATA_FIM = "Data Fim Prevista"
    const val DETALHES_RENOVACOES = "Renovações"
    const val DETALHES_PAGAMENTO = "Pagamento"
    const val DETALHES_ENTREGA = "Entrega"
    const val DETALHES_COLETA = "Coleta"
    const val DETALHES_NOTA_FISCAL = "Nota Fiscal"
    const val DETALHES_MARCAR_PAGO = "Marcar como Pago"
    const val DETALHES_MARCAR_ENTREGUE = "Marcar como Entregue"
    const val DETALHES_MARCAR_COLETADO = "Marcar como Coletado"
    const val DETALHES_MARCAR_NOTA_EMITIDA = "Marcar como Emitida"
    const val DETALHES_RENOVAR = "Renovar Locação"
    const val DETALHES_NOTA_EMITIDA = "Emitida"

    // Renovar Dialog
    const val RENOVAR_TITLE = "Renovar Locação"
    const val RENOVAR_NOVA_DATA = "Nova Data de Fim"
    const val RENOVAR_MANTER_VALOR = "Manter valor atual"
    const val RENOVAR_NOVO_VALOR = "Novo Valor"

    // Entregas Screen
    const val ENTREGAS_TITLE = "Entregas"
    const val ENTREGAS_PENDENTE_SINGULAR = "entrega pendente"
    const val ENTREGAS_PENDENTE_PLURAL = "entregas pendentes"
    const val ENTREGAS_EMPTY_TITLE = "Nenhuma entrega pendente"
    const val ENTREGAS_EMPTY_SUBTITLE = "Locações com entrega agendada ou pendente aparecerão aqui"
    const val ENTREGAS_CONFIRMAR = "Confirmar Entrega"
    const val ENTREGAS_VENCIMENTO = "Vencimento"

    // Recebimentos Screen
    const val RECEBIMENTOS_TITLE = "Recebimentos"
    const val RECEBIMENTOS_PENDENTE_SINGULAR = "pagamento pendente"
    const val RECEBIMENTOS_PENDENTE_PLURAL = "pagamentos pendentes"
    const val RECEBIMENTOS_TOTAL = "Total a receber"
    const val RECEBIMENTOS_EMPTY_TITLE = "Nenhum recebimento pendente"
    const val RECEBIMENTOS_EMPTY_SUBTITLE = "Locações com equipamentos coletados e pagamento pendente aparecerão aqui"
    const val RECEBIMENTOS_CONFIRMAR = "Confirmar Recebimento"
    const val RECEBIMENTOS_VALOR = "Valor a receber"
    const val RECEBIMENTOS_PERIODO = "Período"
    const val RECEBIMENTOS_STATUS = "Status"

    // Clientes Screen
    const val CLIENTES_TITLE = "Clientes"
    const val CLIENTES_NOVO = "Novo"
    const val CLIENTES_BUSCAR = "Buscar cliente..."
    const val CLIENTES_EMPTY_TITLE = "Nenhum cliente cadastrado"
    const val CLIENTES_EMPTY_SUBTITLE = "Cadastre um novo cliente para começar"
    const val CLIENTES_EMPTY_SEARCH_TITLE = "Nenhum cliente encontrado"
    const val CLIENTES_EMPTY_SEARCH_SUBTITLE = "Tente buscar por outro termo"
    const val CLIENTES_CADASTRAR = "Cadastrar Cliente"
    const val CLIENTES_EDITAR = "Editar"
    const val CLIENTES_EXCLUIR = "Excluir"

    // Cliente Form
    const val CLIENTE_FORM_NOVO = "Novo Cliente"
    const val CLIENTE_FORM_EDITAR = "Editar Cliente"
    const val CLIENTE_FORM_NOME = "Nome / Razão Social *"
    const val CLIENTE_FORM_NOME_PLACEHOLDER = "Nome completo ou razão social"
    const val CLIENTE_FORM_CPF_CNPJ = "CPF / CNPJ"
    const val CLIENTE_FORM_CPF_CNPJ_PLACEHOLDER = "000.000.000-00"
    const val CLIENTE_FORM_TELEFONE = "Telefone / WhatsApp *"
    const val CLIENTE_FORM_TELEFONE_PLACEHOLDER = "(00) 00000-0000"
    const val CLIENTE_FORM_EMAIL = "E-mail"
    const val CLIENTE_FORM_EMAIL_PLACEHOLDER = "email@exemplo.com"
    const val CLIENTE_FORM_ENDERECO = "Endereço"
    const val CLIENTE_FORM_ENDERECO_PLACEHOLDER = "Endereço completo"
    const val CLIENTE_FORM_NOTA_FISCAL = "Precisa de Nota Fiscal por padrão"
    const val CLIENTE_FORM_CADASTRAR = "Cadastrar"
    const val CLIENTE_FORM_ATUALIZAR = "Atualizar"

    // Equipamentos Screen
    const val EQUIPAMENTOS_TITLE = "Equipamentos"
    const val EQUIPAMENTOS_NOVO = "Novo"
    const val EQUIPAMENTOS_BUSCAR = "Buscar equipamento..."
    const val EQUIPAMENTOS_EMPTY_TITLE = "Nenhum equipamento cadastrado"
    const val EQUIPAMENTOS_EMPTY_SUBTITLE = "Cadastre um novo equipamento para começar"
    const val EQUIPAMENTOS_EMPTY_SEARCH_TITLE = "Nenhum equipamento encontrado"
    const val EQUIPAMENTOS_EMPTY_SEARCH_SUBTITLE = "Tente buscar por outro termo"
    const val EQUIPAMENTOS_CADASTRAR = "Cadastrar Equipamento"
    const val EQUIPAMENTOS_EDITAR = "Editar"
    const val EQUIPAMENTOS_EXCLUIR = "Excluir"
    const val EQUIPAMENTOS_ALUGADO = "Alugado"
    const val EQUIPAMENTOS_DISPONIVEL = "Disponível"
    const val EQUIPAMENTOS_PRECO_LOCACAO = "Preço locação"
    const val EQUIPAMENTOS_VALOR_COMPRA = "Valor de compra"

    // Equipamento Form
    const val EQUIPAMENTO_FORM_NOVO = "Novo Equipamento"
    const val EQUIPAMENTO_FORM_EDITAR = "Editar Equipamento"
    const val EQUIPAMENTO_FORM_NOME = "Nome do Equipamento *"
    const val EQUIPAMENTO_FORM_NOME_PLACEHOLDER = "Ex: Betoneira 400L"
    const val EQUIPAMENTO_FORM_CATEGORIA = "Categoria *"
    const val EQUIPAMENTO_FORM_CATEGORIA_PLACEHOLDER = "Ex: Betoneira, Martelete, Escora"
    const val EQUIPAMENTO_FORM_IDENTIFICACAO = "Identificação / Patrimônio"
    const val EQUIPAMENTO_FORM_IDENTIFICACAO_PLACEHOLDER = "Ex: #001, PAT-123"
    const val EQUIPAMENTO_FORM_PRECO = "Preço Padrão de Locação *"
    const val EQUIPAMENTO_FORM_PRECO_PLACEHOLDER = "0.00"
    const val EQUIPAMENTO_FORM_VALOR_COMPRA = "Valor de Compra"
    const val EQUIPAMENTO_FORM_VALOR_COMPRA_PLACEHOLDER = "0.00"
    const val EQUIPAMENTO_FORM_OBSERVACOES = "Observações"
    const val EQUIPAMENTO_FORM_OBSERVACOES_PLACEHOLDER = "Informações adicionais sobre o equipamento"
    const val EQUIPAMENTO_FORM_CADASTRAR = "Cadastrar"
    const val EQUIPAMENTO_FORM_ATUALIZAR = "Atualizar"

    // Common
    const val COMMON_VOLTAR = "Voltar"
    const val COMMON_FECHAR = "Fechar"
    const val COMMON_CANCELAR = "Cancelar"
    const val COMMON_CONFIRMAR = "Confirmar"
    const val COMMON_SALVAR = "Salvar"
    const val COMMON_EDITAR = "Editar"
    const val COMMON_EXCLUIR = "Excluir"
    const val COMMON_ERRO = "Erro"
    const val COMMON_SUCESSO = "Sucesso"
    const val COMMON_CARREGANDO = "Carregando..."
    const val COMMON_CLIENTE_NAO_ENCONTRADO = "Cliente não encontrado"
    const val COMMON_EQUIPAMENTO_NAO_ENCONTRADO = "Equipamento não encontrado"
    const val COMMON_ERRO_DESCONHECIDO = "Erro desconhecido"

    // Validation Messages
    const val VALIDATION_SELECIONE_CLIENTE = "Selecione um cliente"
    const val VALIDATION_SELECIONE_EQUIPAMENTO = "Selecione um equipamento"
    const val VALIDATION_INFORME_DATA_FIM = "Informe a data de fim prevista"
    const val VALIDATION_INFORME_VALOR = "Informe um valor válido"
    const val VALIDATION_INFORME_DATA_ENTREGA = "Informe a data de entrega prevista"

    // Success Messages
    const val SUCCESS_LOCACAO_CRIADA = "Locação criada com sucesso!"
    const val SUCCESS_LOCACAO_RENOVADA = "Locação renovada com sucesso!"
    const val SUCCESS_PAGAMENTO_MARCADO = "Pagamento marcado como pago!"
    const val SUCCESS_ENTREGA_MARCADA = "Equipamento marcado como entregue!"
    const val SUCCESS_COLETA_MARCADA = "Equipamento marcado como coletado!"
    const val SUCCESS_NOTA_EMITIDA = "Nota fiscal marcada como emitida!"
    const val SUCCESS_CLIENTE_SALVO = "Cliente salvo com sucesso!"
    const val SUCCESS_CLIENTE_EXCLUIDO = "Cliente excluído com sucesso!"
    const val SUCCESS_EQUIPAMENTO_SALVO = "Equipamento salvo com sucesso!"
    const val SUCCESS_EQUIPAMENTO_EXCLUIDO = "Equipamento excluído com sucesso!"

    // Error Messages
    const val ERROR_LOCACAO_NAO_ENCONTRADA = "Locação não encontrada"
    const val ERROR_CRIAR_LOCACAO = "Erro ao criar locação"
    const val ERROR_RENOVAR_LOCACAO = "Erro ao renovar locação"
    const val ERROR_MARCAR_PAGAMENTO = "Erro ao marcar pagamento"
    const val ERROR_MARCAR_ENTREGA = "Erro ao marcar entrega"
    const val ERROR_MARCAR_COLETA = "Erro ao marcar coleta"
    const val ERROR_MARCAR_NOTA = "Erro ao marcar nota"
    const val ERROR_SALVAR_CLIENTE = "Erro ao salvar cliente"
    const val ERROR_EXCLUIR_CLIENTE = "Erro ao excluir cliente"
    const val ERROR_SALVAR_EQUIPAMENTO = "Erro ao salvar equipamento"
    const val ERROR_EXCLUIR_EQUIPAMENTO = "Erro ao excluir equipamento"

    // Helper functions for pluralization
    fun locacoesAtivas(count: Int) = "$count ${if (count == 1) LOCACOES_ATIVA_SINGULAR else LOCACOES_ATIVA_PLURAL}"
    fun locacoesFinalizadas(count: Int) = "$count ${if (count == 1) LOCACOES_FINALIZADA_SINGULAR else LOCACOES_FINALIZADA_PLURAL}"
    fun entregasPendentes(count: Int) = "$count ${if (count == 1) ENTREGAS_PENDENTE_SINGULAR else ENTREGAS_PENDENTE_PLURAL}"
    fun recebimentosPendentes(count: Int) = "$count ${if (count == 1) RECEBIMENTOS_PENDENTE_SINGULAR else RECEBIMENTOS_PENDENTE_PLURAL}"
    fun clientesCadastrados(count: Int) = "$count clientes cadastrados"
    fun equipamentosCadastrados(count: Int) = "$count equipamentos cadastrados"
    fun formatId(id: String) = "ID: $id"
    fun formatPrevista(data: String) = "Prevista: $data"
    fun formatDataPrevista(data: String) = "Data prevista: $data"
}
